---

version: '2.3'

services:
  webapp:
    image: unifi-controller:latest
    build: ..
    environment:
      MONGO_HOST: persistence
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - persistence
    volumes:
       - webapp-backups:/usr/lib/unifi/data/backup/autobackup
    networks:
      - unifi_controller
  persistence:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - unifi_controller

volumes:
  webapp-backups:
  mongo-data:

networks:
  unifi_controller:
